### ISSUE TITLE
Support for direct-access files (was: Why write the file handle in the file?)

### ISSUE THREAD

**Issue by fujisan43** [traktofon/FortranFiles.jl#1]
When I open a file in `write` mode, and just write `f` and `i`, it should not write the value of `f` in the file, only the value of `i`.
```
f = FortranFile("data.bin", "w")
i = Int32(5)
write(f,i)
close(f)
```
The file `data.bin` has a size of 12 bytes and not 4!
Despite what is written in your doc, the above Julia code is NOT equivalent to
```
open(10, file="data2.bin", access="direct", form="unformatted", recl=1)
write(10,rec=1) 5
close(10)
```

For the same reason, I cannot read existing binary files with FortranFiles `read` function because it is trying to read `f`.
```
x = read(f, (Float64,p))
```
You should fix this somehow.

**Comment by traktofon** [comment]
Hi,

sorry for the late reply. This package currently only supports sequential access mode, but you are using direct access mode. The [documentation](https://traktofon.github.io/FortranFiles.jl/latest/) does mention this. Personally I have no experience with direct-access files in Fortran, which explains the lack of this feature. I agree it would be nice to support these files eventually.

So the extra bytes which this package tries to read/write are not from `f`, but from the record markers (4 bytes before and after each record).

**Comment by traktofon** [comment]
@fujisan43: BTW, if you want to help making support for direct-access files a reality, do you happen to have any documentation for how these files are structured on the binary level? I believe there may be differences between compilers as well, so if you have any information about idiosyncratic behavior of compilers w.r.t. direct-access files, please let me know.

**Comment by fujisan43** [comment]
Hi,
I didn't see the documentation.
You can find info on fortran here: https://software.intel.com/en-us/node/678956

Consider an array declared as:

`real :: farray(n1,n2)`

To open a fortran binary file, you would do:

`open(iunit, file="myfile", access="direct", form="unformatted", recl=n1*n2)`

iunit is an integer (the file handler), nelem is the record length you will read.

To read, you would do

`read(iunit, rec=1) farray`

rec=1 means you read the first record and store it in farray. So you read the whole file at once and store it in farray.

you can also read element by element. Then you must open the file like this:

`open(iunit, file="myfile", access="direct", form="unformatted", recl=1)`

notice recl=1

```
k=1
do j = 1,n2
  do i = 1,n1
    read(iunit, rec=k) farray(i,j)
  k = k+1
  enddo
enddo

```
So, you first read rec 1, then rec 2, rec 3 ... until rec `n1*n2`. This is much slower than read the file as a single record and opening the file with recl=`n1*n2`.

Here is a little program:

```
    ! compile with : gfortran -o write_read write_read.f90
    ! or : ifort -o write_read write_read.f90

    program write_read
    
    integer(kind=4) :: i, j, n1, n2, ierr
    integer(kind=8) :: reclen
    real(kind=4), allocatable :: fr(:,:), fw(:,:)
    
    n1 = 10
    n2 = 20
    
    write(*,*) "---- WRITING ------------------------------------"
    write(*,*) "Allocating memory for array 'fw'"
    allocate(fw(n1,n2))

    ! Getting record length for 'open'
    inquire(iolength=reclen) fw
    
    ! Populating farray
    do j = 1,n2
        do i = 1,n1
            fw(i,j) = real(i)*real(j)
        enddo
    enddo
    
    ! open file 'file.bin'. If it does not exist, it is created.
    open(10, file="file.bin", access="direct", form="unformatted", recl=reclen, iostat=ierr)
    if (ierr > 0) write(*,*) "Error opening file for writing"
    if (ierr <= 0) write(*,*) "File opened for writing!"
    write(10, rec=1) fw
    close(10)

    !! You could do:
    !open(10, file="file.bin", access="direct", form="unformatted", recl=1)
    !k = 1
    !do j = 1,n2
    !do i = 1,n1
    !write(10, rec=k) fw(i,j)
    !k = k+1
    !enddo
    !enddo
    !close(10)

    write(*,*) "Array 'fw' has been written to file 'file.bin'!"

    write(*,*) "De-allocating memory for array 'fw'"
    deallocate(fw)
    
    write(*,*) "---- READING ------------------------------------"
    write(*,*) "Allocating memory for array 'fw'"
    allocate(fr(n1,n2))

    open(10, file="file.bin", access="direct", form="unformatted", recl=reclen, iostat=ierr)
    if (ierr > 0) write(*,*) "Error opening file for reading"
    if (ierr <= 0) write(*,*) "File opened for reading!"
    read(10,rec=1) fr
    close(10)

    write(*,*) "File file.bin has been read! Data has been stored in array 'fr'"

    write(*,*) "Here is what was stored in array 'fr'!"
    do i = 1,n1
        write(*,*) (fr(i,j), j=1,n2)
    enddo

    write(*,*) "De-allocating memory for array 'fr'"
    deallocate(fr)

    write(*,*) "==== END ===="
    
    end

```

Hope this helps a bit.

**Comment by traktofon** [comment]
> To open a fortran binary file, you would do:
> `open(iunit, file="myfile", access="direct", form="unformatted", recl=n1*n2)`

That opens a file in **direct access** mode. Such a file contains records that all have the same fixed size (given by recl). This package currently supports only **sequential access** mode, in which records can have variable size. This is the default, most commonly used, and most portable access mode.

What I was asking for is not how to open, read, or write data in Fortran, but how exactly that data will be stored on disk, because I need to know that in order to make Julia read it correctly. To illustrate some of the pitfalls:

- In sequential access mode, each record contains not just the binary data you write, but is pre- and postfixed by _record markers_ which have to be dealt with. Furthermore, if you write more than 2GiB at once, the record will be split into subrecords, and this needs to be handled. But the format of the record markers is not standardized!
- So are there any record markers in direct access mode? Luckily, the Intel documentation you linked does contain [some info](https://software.intel.com/en-us/node/678405) about this, which indicates that there are no such markers (unless the "vms" option is set, which I assume to be very legacy and decide to ignore at the moment). Of course this is specific to ifort, other compilers might handle it differently. But gfortran seems to do the same.
- In direct access mode, you must specify `recl`, but what does it mean? By default, gfortran interprets this as number of bytes, but ifort as number of 4-byte words. See for example [this question on Stackoverflow](https://stackoverflow.com/questions/32686720/reading-writing-fortran-direct-access-unformatted-files-with-different-compilers). It is not standardized!

> you can also read element by element. Then you must open the file like this:
> `open(iunit, file="myfile", access="direct", form="unformatted", recl=1)`
> notice recl=1

This `recl=1` will only work with ifort, where it means a record length of 4 bytes, just matching the storage size of `real(kind=4)`. gfortran will understand this as record length of 1 bytes, and attempting to read a `real(kind=4)` will likely produce an I/O error. However, your example program does the right thing by using the `inquire` statement to obtain the record length needed for a specific array.

But based on the limited info I have gathered, I can implement some support for direct access mode, assuming that there are no record markers to deal with. This should be okay for compatibility with ifort and gfortran.

**Comment by traktofon** [comment]
@fujisan43: I have checked in a new git branch with support for direct access mode. If you would like to test it, please use the following in Julia:
```
Pkg.checkout("FortranFiles", "directaccess")
```
Here is an example Julia session showing how to use the new functionality for reading the file produced by your example program:
```julia
julia> using FortranFiles

julia> fr=Array{Float32}(10,20);

julia> f=FortranFile("file.bin", access="direct", recl=sizeof(fr))
FortranFile(IOStream(<file file.bin>)), native byte order, direct-access, 800-byte records

julia> read(f, rec=1, fr)
10×20 Array{Float32,2}:
  1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0   10.0   11.0   12.0   13.0   14.0   15.0   16.0   17.0   18.0   19.0   20.0
  2.0   4.0   6.0   8.0  10.0  12.0  14.0  16.0  18.0   20.0   22.0   24.0   26.0   28.0   30.0   32.0   34.0   36.0   38.0   40.0
  3.0   6.0   9.0  12.0  15.0  18.0  21.0  24.0  27.0   30.0   33.0   36.0   39.0   42.0   45.0   48.0   51.0   54.0   57.0   60.0
  4.0   8.0  12.0  16.0  20.0  24.0  28.0  32.0  36.0   40.0   44.0   48.0   52.0   56.0   60.0   64.0   68.0   72.0   76.0   80.0
  5.0  10.0  15.0  20.0  25.0  30.0  35.0  40.0  45.0   50.0   55.0   60.0   65.0   70.0   75.0   80.0   85.0   90.0   95.0  100.0
  6.0  12.0  18.0  24.0  30.0  36.0  42.0  48.0  54.0   60.0   66.0   72.0   78.0   84.0   90.0   96.0  102.0  108.0  114.0  120.0
  7.0  14.0  21.0  28.0  35.0  42.0  49.0  56.0  63.0   70.0   77.0   84.0   91.0   98.0  105.0  112.0  119.0  126.0  133.0  140.0
  8.0  16.0  24.0  32.0  40.0  48.0  56.0  64.0  72.0   80.0   88.0   96.0  104.0  112.0  120.0  128.0  136.0  144.0  152.0  160.0
  9.0  18.0  27.0  36.0  45.0  54.0  63.0  72.0  81.0   90.0   99.0  108.0  117.0  126.0  135.0  144.0  153.0  162.0  171.0  180.0
 10.0  20.0  30.0  40.0  50.0  60.0  70.0  80.0  90.0  100.0  110.0  120.0  130.0  140.0  150.0  160.0  170.0  180.0  190.0  200.0
```
Note the use of `sizeof` which does the same as the `inquire` statement in Fortran here.
Writing files in direct access mode is also supported.
Please refer to Julia's built-in help for `FortranFile`, `read`, and `write` for more info.

If you can, please test this branch and report any problems or success stories here. Thanks!

**Comment by fujisan43** [comment]
There is an option for ifort compiler : `-assume byterecl`
- If you don't use it, then `recl=n` means you will read `n` elements.
- if you use that option, then you must specify the byte size to read in recl: `recl=4*n` or `recl=8*n` depending on how your array is defined: `real(4)` or `real(8)`.

you can compile with `ifort -o write_read write_read.f90` or with `ifort -o write_read write_read.f90 -assume byterecl`, it won't change the output and `reclen` will be `200` or `800`.

I tried the new version version of FortranFile. Your example is working.
But if I want to read the file element by element with
`f=FortranFile("file.bin", access="direct", recl=4)`
I cannot read the first element with 
```
julia> read(f, rec=1, fr[1])
ERROR: MethodError: no method matching read_spec(::FortranFiles.FixedLengthRecord{Int64,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Float32)
Closest candidates are:
  read_spec(::FortranFiles.Record, ::Type{Int8}) at /home/zaira/beauduin/.julia/v0.5/FortranFiles/src/read.jl:60
  read_spec{T}(::FortranFiles.Record, ::Type{T}) at /home/zaira/beauduin/.julia/v0.5/FortranFiles/src/read.jl:65
  read_spec{T,N}(::FortranFiles.Record, ::Array{T,N}) at /home/zaira/beauduin/.julia/v0.5/FortranFiles/src/read.jl:69
  ...
 in fread(::FortranFiles.FortranFile{FortranFiles.DirectAccess,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Float32) at /home/zaira/beauduin/.julia/v0.5/FortranFiles/src/read.jl:46
 in #read#5(::Int64, ::Function, ::FortranFiles.FortranFile{FortranFiles.DirectAccess,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Float32, ::Vararg{Float32,N}) at /home/zaira/beauduin/.julia/v0.5/FortranFiles/src/read.jl:35
 in (::Base.#kw##read)(::Array{Any,1}, ::Base.#read, ::FortranFiles.FortranFile{FortranFiles.DirectAccess,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Float32) at ./<missing>:0
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
```

**Comment by traktofon** [comment]
When reading, you have to pass either an Array or a DataType. `fr[1]` is neither, it is a Float32. Please try:
```
fr[1] = read(f, rec=1, Float32)
```

**Comment by fujisan43** [comment]
Ok. It works. Thanks.

**Comment by traktofon** [comment]
You said:

> There is an option for ifort compiler : -assume byterecl
>     If you don't use it, then recl=n means you will read n elements.
>     if you use that option, then you must specify the byte size to read in recl: recl=4*n or recl=8*n depending on how your array is defined: real(4) or real(8).

That is not correct. See Intel's documentation [here](https://software.intel.com/en-us/node/678857#CCF11AF5-EAFE-487E-8A36-BE7B3AEE6474):

> If the file is connected for formatted data transfer, the value must be expressed in bytes (characters). Otherwise, the value is expressed in 4-byte units (longwords). If the file is connected for unformatted data transfer, the value can be expressed in bytes if compiler option assume byterecl is specified.

Hence for unformatted files, recl is specified in 4-byte units, or in 1-byte units only if the byterecl switch is used.

Also, you state the `recl` specifies how many bytes you will read. I have to nitpick on that: It specifies how long the records in the file are. You may as well read or write less bytes than that.

**Comment by traktofon** [comment]
@fujisan43: a new commit has been pushed. It contains a fix for writing data. It is recommended to update.

**Comment by fujisan43** [comment]
I have a problem reading with a 3D array:
```
vp = Array{Float32}(n1,n2,n3)
g = FortranFile(bin_file, access="direct", recl=sizeof(vp))
read(g, rec=1, vp)
close(g)
```
and the error message is
```
ERROR: LoadError: EOFError: read end of file
 in unsafe_read(::FortranFiles.FixedLengthRecord{Int64,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Ptr{UInt8}, ::UInt64) at .julia/v0.5/FortranFiles/src/fixedlengthrecords.jl:36
 in read!(::FortranFiles.FixedLengthRecord{Int64,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Array{Float32,3}) at ./io.jl:248
 in read_spec at .julia/v0.5/FortranFiles/src/read.jl:69 [inlined]
 in fread(::FortranFiles.FortranFile{FortranFiles.DirectAccess,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Array{Float32,3}) at .julia/v0.5/FortranFiles/src/read.jl:46
 in #read#5(::Int64, ::Function, ::FortranFiles.FortranFile{FortranFiles.DirectAccess,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Array{Float32,3}, ::Vararg{Array{Float32,3},N}) at .julia/v0.5/FortranFiles/src/read.jl:35
 in (::Base.#kw##read)(::Array{Any,1}, ::Base.#read, ::FortranFiles.FortranFile{FortranFiles.DirectAccess,FortranFiles.Conversion{Base.#identity,Base.#identity}}, ::Array{Float32,3}) at ./<missing>:0
while loading Sources/Julia-tests/read_test.jl, in expression starting on line 33

```

**Comment by traktofon** [comment]
So it attempts to read beyond the end of the file. Could you post the file in question, or the Fortran code that produced it? Otherwise it's impossible to tell what's going on.

**Comment by fujisan43** [comment]
Here is the piece of code I am using. 

How can I transfer the file?

```
n1 = 1001
n2 = 4401
n3 = 20

bin_file = "vp.bin"

vp = Array{Float32}(n1,n2,n3)

g = FortranFile(bin_file, access="direct", recl=sizeof(vp))
read(g, rec=1, vp)
close(g)
```

**Comment by fujisan43** [comment]
I found out I was reading the wrong file.
Everything is fine.

**Comment by traktofon** [comment]
Glad to hear it. Thanks for the update.

**Comment by traktofon** [comment]
@fujisan43: I've made a release for the new version of this package (v0.3.0). Since I previously asked you to switch to the master version, you might now want to go back to the regular version. To do so, please use
```
Pkg.free("FortranFiles")
Pkg.update()
```
in the Julia REPL.
